services:

  mariadb:
    image: mariadb:11
    container_name: biblioteca_db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: biblioteca
      MARIADB_USER: laravel
      MARIADB_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: biblioteca_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      UPLOAD_LIMIT: 300M
    ports:
      - "8080:80"
    depends_on:
      mariadb:
        condition: service_healthy

volumes:
  mariadb_data:
